### ISSUE TITLE
Could you provide python version of DistanceBtnScanContexts.m?

### ISSUE THREAD

**Issue by kxhit** [irapkaist/scancontext#1]
Hi! Thanks for sharing your code!
Could you provide the python version of 'DistanceBtnScanContexts.m', which calculates the distance between two ScanContexts? If so, I will appreciate it a lot! Thanks!

**Comment by ayoungk** [comment]
Not at this moment. Feel free to grab our Matlab code and implement/modify to other languages that you want.

**Comment by kxhit** [comment]
@ayoungk Hi!
I pull a [request](https://github.com/irapkaist/scancontext/pull/2)

Hi!
I add  the python-version of calculating distance between two ScanContexts. Modified from 'DistanceBtnScanContexts.m'.
I set the SC size with 20x60 as the basic.m does, but I find the ScanContexts generated from 'make_sc_example.py' is a little different with 'Ptcloud2ScanContext.m'. So the final distance between the python version and matlab  version is a little different. I think the implementation of 'Distance_SC.py' is OK. Could you help me figure it out?
Thanks a lot!

Results:
    # python result
    # 0.10860358309493079
    # 0.4954163429642825
    # 0.4809364940958847
    # 0.13027243597096394

    # matlab result
    # 0.1426
    # 0.5109
    # 0.4902
    # 0.1151

**Comment by kxhit** [comment]
[Add python-version](https://github.com/irapkaist/scancontext/pull/2) Merged & Closed

**Comment by kxhit** [comment]
Hi! Will the code of SCI (2019 RA-L, CNN-version Scan Context) be released? Thanks.
