### ISSUE TITLE
How to run this algorithm using our rosbag?

### ISSUE THREAD

**Issue by yutouwd** [irapkaist/scancontext#11]
Hello @gisbi-kim,

Thanks for your outstanding work. I have successfully run the demo of place recognition in Matlab. Now I want to try it on our rosbag. How can I transform the rosbag topic ```velodyne_points``` into binary file like the Kitti velodyne laser data?

**Comment by gisbi-kim** [comment]
for the rostopic subscribing example, please see the lidar-slam integrated examples
here:
- https://github.com/irapkaist/SC-LeGO-LOAM
- https://github.com/gisbi-kim/SC-LIO-SAM

**Comment by yutouwd** [comment]
Thanks for your reply. I will try it :)

**Comment by yutouwd** [comment]
Hi @gisbi-kim,

I have tried SC-LeGO-LOAM and it has remarkable performance when building map. How can I do a localization or place recognition task by using Scan Context with cpp code?

**Comment by gisbi-kim** [comment]
@yutouwd 
I mentioned at https://github.com/irapkaist/SC-LeGO-LOAM/issues/14

Thank you!
