### ISSUE TITLE
how to find which frames in kitti data are the loop frame

### ISSUE THREAD

**Issue by fttps** [irapkaist/scancontext#12]
Hello @gisbi-kim , Thanks for your outstanding work. 
I have made some changes to scan context and I want to know the precision and recall rate of the modified algorithm.
i want to use kitti data to test.  but i don't know which frames in kitti data are the loop frame.
how to get 790 true loops in kitti sequence00.(IROS 18 paper)

should I use poses.txt provide by kiiit or icp to find the loop frames  or some other methods.

Looking forward to your reply，thank you.

**Comment by gisbi-kim** [comment]
thank you for having an interest in our work. 

for the evaluation, 
see here please https://github.com/irapkaist/scancontext/blob/ba81d6e5ba91bf6f3dfeb9153fbcd853d124c250/fast_evaluator/main.m#L78

**Comment by fttps** [comment]
many thanks to you.
