### ISSUE TITLE
Does anyone test the performance using 2D-Lidar?

### ISSUE THREAD

**Issue by sunbingfeng** [irapkaist/scancontext#13]
I think that it may work using 2D-Lidar, but I'm not sure the real call-out accuracy.

Anyone who has already tested it please let me know.

Thanks!

**Comment by gisbi-kim** [comment]
hi @sunbingfeng, sorry for the late response.

I did not test 2D lidar examples, but navtech radar
The navtech radar is originally an image, but using popular radar odometry methods (e.g., Yeti odometry), they  transforms the image into a set of 2D keypoints in the Cartesian metric space. So we can say the thing's nature is equal to the 2D lidar point cloud.

I consume the navtech radar point cloud (ros message is actually pointcloud2 and I used some constant (dummy) value (e.g., = 2) for the z element for all points)  
and the scan context manager runs by using this point cloud and I saw it works. 
please see here. https://github.com/gisbi-kim/navtech-radar-slam

**Comment by sunbingfeng** [comment]
Thanks for your kind response, and I will try later. @gisbi-kim
