### ISSUE TITLE
Time cost of calculating SCs distance and P-R curve.

### ISSUE THREAD

**Issue by kxhit** [irapkaist/scancontext#3]
Hi! @irapkaist  Thanks for opening your code!

Calculating 2 SCs distance is about 0.1s on my PC. I want to plot the P-R curve as your paper, but I find that is very time-consuming. For example, sequence 00 in KITTI has 4000+ frames and I should calculate every frame pair (4000+ x 4000+ / 2 = 8000000+ pairs), which may cost (8000000x0.1s). Is my idea wrong? How should I do to draw the P-R curve as your paper? Thanks a lot!!!

**Comment by irapkaist** [comment]
First thank you for your attention.

We added fast_evaluator, which do the evaluation in an efficient  way; evaluation codes in there does not repeat duplicate calculations.

you can use from here 
https://github.com/irapkaist/scancontext/tree/master/fast_evaluator

how to use it: 
- 1. run main.m (this example is designed for KITTI) 
- 2. run prcurve_drawer.m -> this will make pr_curve figure in the pdf format.

thank you!

**Comment by kxhit** [comment]
@irapkaist  Thank you for your prompt reply! 
Here I have 2 questions:
1. I noticed that you only calculate TN, FN, TP, FP of top1 (of course we can choose top5 or topk) candidates of each query sample. If I want to compare with your result, I should calculate top1(or topk) candidates as you do, right?
2. I think the distance (between target and source) less than threshold (e.g. 5m) and the time larger than threshold (e.g. 30s) could be considered as true loop closure. Continuous adjacent frames should not be considered. (Cause it is too easy.) But there is only distance threshold in your evaluation, which will introduce lots of easy sample pairs and will drown out few true loop closures. I think it is more reasonable to verify only the true loop closures. 

Looking forward to your thoughts. Thanks!

**Comment by irapkaist** [comment]
This is the answer. 

1. yes. you should consider top **_1_** only for answer. 

2. in this line: [revisitness, how_far_apart] = isRevisitGlobalLoc(query_pose, exp_poses(1:end-(num_candidates-1), :), revisit_criteria); the _1:end-(num_candidates-1)_ have an effect that recent near nodes should be not engaged. so you don't need to worry about that.

thank you!

**Comment by kxhit** [comment]
Many thanks to you!
Closed.
