### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rsasaki0109** [irapkaist/scancontext#6]
Thanks for your great work! 
I want to incorporate it in our project, but what about licensing?

**Comment by deen12** [comment]
How did this issue turn out?
I'd like to use it, but I'm hesitant to use it if it's GPL-based license.

**Comment by kissb2** [comment]
@deen12  sorry for the late response. 

We are checking with the funding agent which is a company. Sorry for the delay but it will take a while.

**Comment by deen12** [comment]
I see.
Thank you for your reply.
